### ISSUE TITLE
up-/download not possible

### ISSUE THREAD

**Issue by adiran** [cy33hc/switch-smb-client#3]
Hey
i tried this smb client but i can't up- or download files. When i press X the option to download or upload is grayed out. i can (de)select all, create a new folder, see details or cancle the menu but the options to delete, rename or up-/download are grayed out in the lokal files as well as in the remote files.
I thought it might be because of applet mode, but when i start homebrew in full ram mode and enter the smb-client the behavios is still the same. I confirmed the user i use to access the smb share is able to write on the share and there is enough space available.
Am i doing something wrong or is this a problem with this client?

EDIT: i also tested your switch-ftp-client and got the same problem

**Comment by cy33hc** [comment]
@adiran Sorry. The controls are a little weird at the moment. You need to tag the files with "Y" button first before those menu items are enabled. That will be changed in later release.

**Comment by adiran** [comment]
Ahh yes :) Thank you very much, that was my problem.
